chore: Standardize CI with other projects
omec-project/path_util pull request #2
Opened 2024-01-24 21:53 UTC by ghislainbourgeois

2024-01-24 21:54 UTC, ghislainbourgeois commented
@gab-arrobo , this one also seems ignored by the onf-bot

2024-01-24 22:27 UTC, gab-arrobo commented
@ghislainbourgeois @thakurajayL, I see this repo has only one file that might be relevant (path.go + its test file). What about moving the few things that are important from this repo into the `util` repo? So, we do not have to maintain multiple tiny repos for no reason. What do you guys think?

2024-01-24 22:33 UTC, ghislainbourgeois commented
> @ghislainbourgeois @thakurajayL, I see this repo has only one file that might be relevant (path.go + its test file). What about moving the few things that are important from this repo into the `util` repo? So, we do not have to maintain multiple tiny repos for no reason. What do you guys think?

I think it would make sense, it would involve fixing the imports in other projects, but that should not take too long.

2024-02-20 02:02 UTC, gab-arrobo commented
@ghislainbourgeois, should we close this PR? or should we merge it?

2024-02-20 02:47 UTC, gab-arrobo requested changes
The `license-check` action fails because several files do not have copyright and license headers

2024-02-20 02:47 UTC, gab-arrobo commented on .github/dependabot.yml
> +
```suggestion
```

2024-02-20 02:47 UTC, gab-arrobo commented on .github/workflows/main.yml
> +        uses: golangci/golangci-lint-action@v3.7.0
```suggestion
        uses: golangci/golangci-lint-action@v4.0.0
```

2024-02-20 02:47 UTC, gab-arrobo commented on .github/workflows/main.yml
> +          fossa-api-key: 9dc8fa92e3dd565687317beb87b56d89
```suggestion
          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
```

2024-03-01 00:54 UTC, gab-arrobo commented
@ghislainbourgeois, I am closing this PR given that it is not needed anymore. All of the repos are pointing to `path_util` from `util` repo

2024-03-01 00:54 UTC, closed without merging